import type { Metadata } from "next";
import { Link } from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
       {/* Footer */}
      <footer className="bg-red-900 text-white py-4 px-6 flex justify-between items-center">
        <div className="flex items-center space-x-4">
          <div className="text-yellow-400">🔔</div>
          <span className="font-bold text-lg">Merry Christmas!</span>
        </div>
        <nav className="flex space-x-4">
          <Link href="/friends">Friends</Link>
          <Link href="/tasks">Tasks</Link>
        </nav>
      </footer>
        </body>
    </html>
  );
}
